# Generated by Django 2.2.5 on 2019-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_remove_room_cur_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_person',
            name='seq_id',
            field=models.IntegerField(default=0),
        ),
    ]
