# Generated by Django 2.2.5 on 2019-10-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_room_person_seq_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_person',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
