# Generated by Django 2.2.5 on 2019-10-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_room_person_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_person',
            name='start',
        ),
        migrations.AddField(
            model_name='room',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
