# Generated by Django 2.2.7 on 2019-12-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_auto_20191008_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bot_num',
            field=models.IntegerField(default=0),
        ),
    ]
