num_workers: 90
num_database: 10

ext_server:
  host: "172.18.40.65"
  port: 18888

server:
  host: "172.18.40.66"
  port: 10000

database:
  host: "172.18.40.65"
  port: 3306
  user: "root"
  password: "root"
  table: "poker"
  save_data: True
  
rabbitMQ:
  host: "172.18.40.65"
  username: root
  password: root