server:
  host: "127.0.0.1"
  port: 18888

bot:
  RandomAgent:
    host: "127.0.0.1"
    port: 10020

  CallAgent:
    host: "127.0.0.1"
    port: 10023

  AllinAgent:
    host: "127.0.0.1"
    port: 10022
  
  LuaStack:
    host: "a.xuhang.ink"
    port: 30000
  
  RuleAgent:
    host: "127.0.0.1"
    port: 10029
  
database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "0"
  table: "poker"

rabbitMQ:
  host: "127.0.0.1"  