ext_server:
  host: "bb.xuhang.ink"
  port: 12345

server:
  host: "127.0.0.1"
  port: 10000

bot:
  RandomAgent:
    host: "127.0.0.1"
    port: 20001

  CallAgent:
    host: "127.0.0.1"
    port: 20002

  AllinAgent:
    host: "127.0.0.1"
    port: 20003
  
  LuaStack:
    host: "a.xuhang.ink"
    port: 30000
  
  RuleAgent:
    host: "127.0.0.1"
    port: 20004
  
database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "0"
  table: "poker"

rabbitMQ:
  host: "b.xuhang.ink"
  # host: "127.0.0.1"